apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  name: blog-cert
  namespace: blog
spec:
  secretName: blog-cert # Secret where the certificate will be stored
  duration: 2160h                 # How long the certificate is valid
  renewBefore: 1070h              # When to renew the certificate
  dnsNames:
    - maksym.shemet.blog.smv.pp.ua          # Add additional domains as needed
  issuerRef:
    name: letsencrypt-prod      # The name of your ClusterIssuer or Issuer
    kind: ClusterIssuer 