apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  name: blog-ingress
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - maksym.shemet.blog.smv.pp.ua
      secretName: blog-cert
  rules:
    - host: maksym.shemet.blog.smv.pp.ua
      http:
        paths:
          - path: /
            pathType: ImplementationSpecific
            backend:
              service:
                name: blog-svc
                port:
                  number: 80