apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "2"
    nginx.ingress.kubernetes.io/configuration-snippet: |
      types {
        application/javascript js mjs;
        text/javascript js mjs;
      }
    nginx.ingress.kubernetes.io/server-snippet: |
      # Proper MIME type for JavaScript modules
      map $uri $js_mime_type {
        ~\.mjs$ application/javascript;
        ~\.js$ application/javascript;
        default text/html;
      }
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/cors-allow-methods: "GET, PUT, POST, DELETE, PATCH, OPTIONS"
    nginx.ingress.kubernetes.io/cors-allow-origin: "*"
    nginx.ingress.kubernetes.io/enable-cors: "true"
  name: blog-ingress
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - maksym.shemet.blog.smv.pp.ua
      secretName: blog-cert
  rules:
    - host: maksym.shemet.blog.smv.pp.ua
      http:
        paths:
          - path: /
            pathType: ImplementationSpecific
            backend:
              service:
                name: blog-svc
                port:
                  number: 80